### ISSUE TITLE
Parsing issue with malformed HTML

### ISSUE THREAD

**Issue by nicolasbadia** [thampe/inky#1]
The library truncate the HTML when it is malformed:

```
$inky = new \Hampe\Inky\Inky();
echo $inky->releaseTheKraken('<p>Malformed HTML</a></p><p>Next paragraph</p>');
```

This exemple will return:

```
<p>Malformed HTML</p>
```

**Comment by thampe** [comment]
Hi,

inky uses the [PHP Html Parser](https://github.com/paquettg/php-html-parser) for parsing the HTML. I would have to implement my own parsing algorithm to fix this issue, which I am not planning to do ;). Sorry. Maybe the the developer(s) of the PHP Html Parser can help?

**Comment by nicolasbadia** [comment]
Thanks for the quick answer. I assume the problem is on there side then...
In the case others as the same issue, a quick solution is to use the Tidy library to repair the HTML:

    $tidy = new tidy;
    $body = new tidy->repairString($string, ['show-body-only'=>true], 'utf8');
