### ISSUE TITLE
Inky 1.3.6

### ISSUE THREAD

**Issue by svennis94** [thampe/inky#2]
Hi there!

I was wondering if there are plans / progress in implementing the changes of Inky 1.3.6 to this library. I would like to help but it would be good to know if some parts are already developed.

https://github.com/zurb/inky/releases/tag/v1.3.6

Thanks!

**Comment by thampe** [comment]
Hi,

thanks for your offer. I did not have the time to make any changes to for version 1.3.6 yet. So feel free to to make as many pull requests as you like. 

I have commented the features from 1.3.6 below. I will try to keep this list up to date. 

## Features
- Buttons can now have target attributes
  - not done
- You can now vertically align content in columns and Source order - HTML attributes can now be passed to row’s and columns
  - vertical alignment is not done
  - HTML-Attributes should work, without any extra changes
- Spacer height can now be controlled by media query in HTML
  - not done
- Added data-attribute no-expander to to disable the .expander 
  - not done
- Menu items can now have target attributes - #54 fixes #465
  - not done
- <raw> Inky tag to ignore parsing handlebars and other things that should not be changed
  - not done.

## Bug fixes
- Prevents character encoding in many places 
  - have not yet looked into this one
- Adds default spacer size if none is specified - c17a914
  - _done_, works already
