### ISSUE TITLE
Inlining

### ISSUE THREAD

**Issue by thisisjamessmith** [thampe/inky#3]
Thanks for making this, it's looking very useful. Do you have any plans to integrate Inky's inliner functionality? Or have I missed that somewhere?

**Comment by thampe** [comment]
Hi,

CSS-Inlining is not part of the [original implementation](https://github.com/zurb/inky). And I have no plans to add this functionality either. 

You can use  [Tijs Verkoyen's CssToInlineStyles](https://github.com/tijsverkoyen/CssToInlineStyles), I am using it in my related [project](https://github.com/thampe/ZurbInkBundle). It is easy to use and the results are really good.

**Comment by thisisjamessmith** [comment]
Ah great, thanks for the pointer. I ended up using Premailer's ruby gem and a [php wrapper](https://github.com/onassar/PHP-Premailer) to trigger it. The php library looks like it might be a better choice, nice to avoid the Ruby dependency.
