### ISSUE TITLE
Style tags are being stripped out

### ISSUE THREAD

**Issue by petecoop** [thampe/inky#7]
`<style>` tags are being stripped out when I use this, I'd like to keep them so I can later inline the CSS. I briefly looked into it and I think it's an issue with PHPHtmlParser.

I'm working on a package for Laravel to use this nicely (https://github.com/petecoop/laravel-inky), really thankful you've built a PHP parser for inky!

**Comment by thampe** [comment]
Hi,

thanks for reporting this bug. I updated to the dependencies in `1.3.6.2` to the latest PHPHtmlParser Version (1.7.0). The PHPHtmlParser has has now Option for _not_ stripping out the `<script/>` and `<style />` tags.

**Comment by petecoop** [comment]
awesome thanks
